feature/FC-4-item-add-crud
s-dupuis/formation-christelle pull request #1
Opened 2023-02-15 10:50 UTC by chl-33

2023-02-15 11:03 UTC, s-dupuis requested changes

2023-02-15 11:03 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +  };
Pourquoi toutes tes fonctions sont asynchrones ?

2023-02-15 11:03 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +    const newItem = R.merge({ id: id }, item);
Plutôt que `merge` tu peux regarder du côté de `assoc`

2023-02-15 11:03 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +      return items.splice(index, 1)[0];
En ramda ?

2023-02-15 11:03 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +    return newItem;
Attention il manque la validation décrite dans le ticket : 
![image](https://user-images.githubusercontent.com/16538615/219009980-7549aebf-b073-47e5-a958-7021d17e9c81.png)

2023-02-15 11:03 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +  };
Idem il manque la validation

2023-02-15 11:03 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +      return updatedItem;
Tu peux faire toutes ces actions en ramda pur

2023-02-15 14:48 UTC, s-dupuis requested changes

2023-02-15 14:48 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +    if (R.is(String, item.name) && validateCategory(item.category) && R.is(String, item.group)) {
1. Pour simplifier la validation, je te conseille de regarder du côté de `whereEq`.
2. Il faudrait aussi simuler un peu le comportement d'un vrai enregistrement en base : si l'objet n'est pas valide, on lève une erreur.
3. Étant donné qu'on réutilise la même fonction de validation pour l'update, tu peux sortir cette logique dans une fonction réutilisable

2023-02-15 14:48 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +          group: item => R.propOr('', 'group', item),
Comme toutes les méthodes Ramda sont curryfiées, tu peux simplifier un peu ces lignes

2023-02-15 14:48 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +      R.remove(index, 1, items);
Attention c'est de la programmation fonctionnelle => tes objets ne mutent pas et il faut que tu réassocies le résultat de ton appel dans ta variable

2023-02-15 14:48 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +      R.remove(index, 1, items);
Tu peux mettre cette logique en place en un seul appel avec `reject`

2023-02-15 14:48 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +        R.mergeRight(R.__, updates),
Si tu utilises `mergeLeft` tu n'auras pas besoin du placeholder

2023-02-15 15:17 UTC, JonathanArn commented on server/controllers/ItemMockCtrl.js
> +      }
`index === -1`  peut-être fait en Ramda

Une autre solution, vérifier l'existence de l'item avec `any`

2023-02-15 15:17 UTC, JonathanArn commented on server/controllers/ItemMockCtrl.js
> +      )(items[index]);
ça me parait bien, regardes peut-être plutôt pour utiliser `compose` à la place de `pipe` car c'est plutôt `compose` qui est conventionnellement utilisé chez FASST :)

2023-02-15 15:17 UTC, JonathanArn commented on server/controllers/ItemMockCtrl.js
> +    }
Ici peut être plutôt renvoyer un message indiquant que l'objet updates n'a pas passé la validation.

2023-02-15 15:22 UTC, JonathanArn commented on server/controllers/ItemMockCtrl.js
> +      )(items[index]);
`compose` fait la même chose que `pipe` mais dans l'autre sens

2023-02-16 08:40 UTC, chl-33 commented on server/controllers/ItemMockCtrl.js
> +          group: item => R.propOr('', 'group', item),
resolve conversation

2023-02-16 10:53 UTC, s-dupuis requested changes

2023-02-16 10:53 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +    return false;
Tu peux simplifer :
```suggestion
    return R.or(R.isNil(value), R.is(String, value)));
```

2023-02-16 10:53 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +    name: validateStringOrNil,
Le nom doit aussi être unique

2023-02-16 10:53 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +      )(items[index]);
Pour cibler l'index à mettre à jour, tu peux utiliser `adjust` directement sur ton tableau

2023-02-16 11:11 UTC, JonathanArn commented on server/controllers/ItemMockCtrl.js
> +    console.log('VALUE : ' + value);
console.log à retirer :)

2023-02-16 11:11 UTC, JonathanArn commented on server/controllers/ItemMockCtrl.js
> +    return false;
Pareil que plus bas, tu peux simplement:
`return R.or(R.isNil(value), R.includes(value, categories))`

2023-02-16 12:24 UTC, s-dupuis requested changes

2023-02-16 12:24 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +    (value) => value.includes(name1),
Tu peux utiliser `includes` de Ramda :
```suggestion
    R.includes,
```

2023-02-16 12:24 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +      return R.adjust(index, R.always(updatedItem), items);
Avec `adjust` tu peux plutôt faire ça : 
```suggestion
      return R.adjust(
        index,
        R.compose(
          R.assoc('updatedAt', new Date().toISOString()),
          R.mergeLeft(updates)
        ),  
        items
      );
```

2023-02-16 12:24 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +      return R.adjust(index, R.always(updatedItem), items);
Il faut également penser à mettre ta liste à jour pour que le nouvel item soit pris en compte

2023-02-16 13:36 UTC, s-dupuis requested changes

2023-02-16 13:36 UTC, s-dupuis commented on server/controllers/ItemMockCtrl.js
> +    (value) => R.includes(value, name1),
Pour les paramètres ce serait plutôt l'inverse : 
```suggestion
    (value) => R.includes(name1, value),
```

Qu'on peut simplifier : 
```suggestion
    R.includes(name1),
```

2023-02-16 13:41 UTC, merged