FC-8 mise-en-place-test-unitaire
s-dupuis/formation-christelle pull request #5
Opened 2023-02-22 13:45 UTC by chl-33

2023-02-22 13:58 UTC, s-dupuis requested changes

2023-02-22 13:58 UTC, s-dupuis commented on spec/itemResolver.spec.js
> +  });
tu peux réutiliser `initDb` et `isReady` qui existent déjà

2023-02-22 13:58 UTC, s-dupuis commented on spec/itemResolver.spec.js
> +    const result = await db.collections.items.insertMany([{
il faudrait plutôt passer par ton modèle pour réaliser cette action

2023-02-22 13:58 UTC, s-dupuis commented on spec/itemResolver.spec.js
> +  describe('getById', () => {
attention c'est bien la récupération de la liste qu'on souhaite tester

2023-02-22 14:31 UTC, JonathanArn commented on spec/itemResolver.spec.js
> +const it = mocha.it;
ici pour éviter d'avoir trop de lignes d'imports je pense que tu peux faire:

```
const { expect } = require('chai');
const { describe, beforeEach, afterEach, it } = require('mocha');
```

2023-02-22 14:31 UTC, JonathanArn commented on spec/itemResolver.spec.js
> +  describe('getById', () => {
de plus dans ce test je vois que tu utilise mongoose pour aller chercher un item, tu ne test rien ici du coup à part que mongoose fonctionne bien :)

Le but ici est de tester "...le fonctionnement de la classe d'échange graphQL" tel que décrit dans le ticket, donc ton resolver ;)

2023-02-23 11:24 UTC, s-dupuis requested changes

2023-02-23 11:24 UTC, s-dupuis commented on spec/itemResolver.spec.js
> +      await Promise.resolve();
pourquoi cet appel ?

2023-02-23 11:24 UTC, s-dupuis commented on spec/itemResolver.spec.js
> +    await secondItem.save();
De préférence on va passer par le modèle `server/services/items/Items.js` pour réaliser ces actions

2023-02-23 11:24 UTC, s-dupuis commented on spec/itemResolver.spec.js
> +    await mongoose.connect(MONGODB_URI);
Les deux fonctions du dessus permettre de réaliser la connexion

2023-02-23 12:16 UTC, s-dupuis approved these changes

2023-02-23 12:16 UTC, merged