FC-10 creation-d-un-item
s-dupuis/formation-christelle pull request #7
Opened 2023-02-28 08:41 UTC by chl-33

2023-02-28 08:43 UTC, s-dupuis requested changes

2023-02-28 08:43 UTC, s-dupuis commented on app/pages/Items/CreateForm.js
> +              })}>
Tu n'appelles pas ta mutation ?

2023-02-28 08:43 UTC, s-dupuis commented on app/pages/Items/index.js
> +                <th scope="col" className="bg-blue-100 border text-left px-8 py-4">Item Group</th>
Etant donné que les classes sont les mêmes on pourrait en faire un composant générique

2023-02-28 08:43 UTC, s-dupuis commented on app/pages/Items/index.js
> +                    <td className="border text-center px-8 py-4">{item?.group}</td>
Idem ici

2023-02-28 08:45 UTC, chl-33 commented on app/pages/Items/CreateForm.js
> +              })}>
Visiblement mon code a disparu :(

2023-02-28 11:18 UTC, chl-33 commented on app/pages/Items/CreateForm.js
> +              })}>
En fait tout le code est dans l'index.js car je n'ai pas réussi à le sortir dans le CreateForm, j'aurai dû le supprimer.

2023-02-28 11:19 UTC, chl-33 commented on app/pages/Items/index.js
> +                    <td className="border text-center px-8 py-4">{item?.group}</td>
J'ai essayé de créer une nouvelle classe item.css, mais je n'arrive pas à la lier à mon tableau

2023-02-28 12:22 UTC, s-dupuis commented on app/pages/Items/index.js
> +                    <td className="border text-center px-8 py-4">{item?.group}</td>
tu peux faire un composant react : 
```jsx
const ValueCell = ({ children }) => {
  return  <td className="border text-center px-8 py-4">{children}</td>;
};

2023-02-28 13:45 UTC, JonathanArn commented on app/pages/Items/index.js
> +              </>
Ce serait bien de le sortir dans un composant. D'ailleurs le tableau de liste d'items aussi, découper en composant permet la réutilisation mais aussi une meilleure relecture et donc maintenabilité du code.

2023-03-01 08:08 UTC, s-dupuis requested changes

2023-03-01 08:08 UTC, s-dupuis commented on app/pages/Items/List.js
> +              }
Je pense que tu dois avoir des erreurs dans la console de ton navigateur car il manque la propriété `key`

2023-03-01 10:15 UTC, JonathanArn commented on app/pages/Items/List.js
> +  };
Ce serait plus propre et plus modulaire de déclarer ce composant en dehors de `List`. Idem pour `ValueCellTd`

2023-03-02 08:24 UTC, s-dupuis approved these changes

2023-03-02 08:40 UTC, merged